from __future__ import annotations

import argparse
from datetime import UTC, datetime
import sys
from pathlib import Path

from .config import load_config
from .notifiers import EmailNotifier
from .pipeline import run_once
from .storage import Storage


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="reddit-ideas",
        description="Scan selected subreddits and generate idea CSV/report outputs.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("config.toml"),
        help="Path to config.toml (default: ./config.toml if present).",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)
    run_parser = subparsers.add_parser("run-once", help="Run one scan/report cycle.")
    run_parser.add_argument(
        "--period", choices=["daily", "weekly"], default="daily", help="Report window."
    )

    email_parser = subparsers.add_parser(
        "test-email", help="Send a test email using configured SMTP settings."
    )
    email_parser.add_argument(
        "--subject",
        default="Reddit Ideas SMTP Test",
        help="Email subject for the test message.",
    )
    email_parser.add_argument(
        "--body",
        default="SMTP test successful. This confirms your Reddit Ideas email configuration works.",
        help="Email body for the test message.",
    )

    log_parser = subparsers.add_parser("show-runs", help="Print recent run logs.")
    log_parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="Maximum number of run log entries to show.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    config = load_config(config_path=args.config)

    if args.command == "run-once":
        result = run_once(config=config, period=args.period)
        print(f"Run status: {result.status}")
        print(
            f"Stats: fetched_posts={result.fetched_posts}, "
            f"extracted_ideas={result.extracted_ideas}, window_ideas={result.window_ideas}, "
            f"email_sent={result.email_sent}"
        )
        print(f"Message: {result.message}")
        if result.csv_path is not None:
            print(f"CSV: {result.csv_path}")
        if result.report_path is not None:
            print(f"Report: {result.report_path}")
        return 0

    if args.command == "test-email":
        if config.smtp is None:
            print(
                "SMTP is not configured. Add [smtp] host/port/user/password/email_to "
                "in config.toml or set REDDIT_IDEAS_SMTP_* env vars."
            )
            return 2

        config.output_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now(tz=UTC).strftime("%Y%m%d_%H%M%S")
        probe_path = config.output_dir / f"email_test_{timestamp}.md"
        probe_path.write_text(
            "# SMTP Probe\n\n"
            "This file was generated by `reddit-ideas test-email`.\n",
            encoding="utf-8",
        )

        notifier = EmailNotifier(
            host=config.smtp.host,
            port=config.smtp.port,
            user=config.smtp.user,
            password=config.smtp.password,
            email_to=config.smtp.email_to,
        )
        notifier.send(subject=args.subject, body=args.body, report_path=probe_path)
        print(f"Test email sent successfully to {config.smtp.email_to}.")
        print(f"Attachment: {probe_path}")
        return 0

    if args.command == "show-runs":
        storage = Storage(config.data_dir / "reddit_ideas.db")
        logs = storage.list_run_logs(limit=args.limit)
        if not logs:
            print("No run logs found.")
            return 0

        for log in logs:
            print(
                f"run_id={log.run_id} period={log.period} day={log.run_day_utc} "
                f"status={log.status} fetched={log.fetched_posts} ideas={log.extracted_ideas} "
                f"window={log.window_ideas} email_sent={log.email_sent} "
                f"start_utc={log.run_started_utc} finish_utc={log.run_finished_utc}"
            )
            if log.message:
                print(f"  message={log.message}")
        return 0

    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
